import { Dimensions } from "react-native";

export const BANNER_H = Dimensions.get('window').height * 0.84;
export const TOPNAVI_H = 50;

// export const API_BASE_URL = 'https://zpiyushviiitoutlets-backend.onrender.com';
// export const VERIFYOTP_ENDPOINT = '/verifyotp';
// export const RESENDOTP_ENDPOINT = '/resendotp';
// export const LOGIN_ENDPOINT = '/login';
// export const REGISTER_ENDPOINT = '/register';
// export const USERSDATA_ENDPOINT = '/userdata';
// export const ADDOUTLET_ENDPOINT = '/addoutlet';
// export const ADDMENU_ENDPOINT = '/addmenu';
// export const USEROUTLETS_ENDPOINT = '/useroutlets';
// export const USERMENU_ENDPOINT = '/usermenu';
// export const ALLOUTLETS_ENDPOINT = '/alloutlets';
// export const ALLOUTLETS2_ENDPOINT = '/alloutlets2';
// export const ORDERS_ENDPOINT = '/createorder';
// export const ORDERSSELLER_ENDPOINT = '/getorderseller';
// export const ORDERSBUYER_ENDPOINT = '/getorderbuyer';
// export const ACCEPTORDER_ENDPOINT = '/acceptOrder';
// export const DECLINEORDER_ENDPOINT = '/declineOrder';
// export const CHANGEORDERSTATUS_ENDPOINT = '/changeOrderStatus';
// export const STORETOKENFCM_ENDPOINT = '/storetoken';
// export const ORDERHISTORYDATA_ENDPOINT = '/orderhistorydata';

export const API_BASE_URL = 'http://10.7.5.82';
export const VERIFYOTP_ENDPOINT = '5001/verifyotp';
export const RESENDOTP_ENDPOINT = '5001/resendotp';
export const LOGIN_ENDPOINT = '5001/login';
export const REGISTER_ENDPOINT = '5001/register';
export const USERSDATA_ENDPOINT = '5001/userdata';
export const ADDOUTLET_ENDPOINT = '5001/addoutlet';
export const ADDMENU_ENDPOINT = '5001/addmenu';
export const USEROUTLETS_ENDPOINT = '5001/useroutlets';
export const USERMENU_ENDPOINT = '5001/usermenu';
export const ALLOUTLETS2_ENDPOINT = '5001/alloutlets2';
export const ALLOUTLETS_ENDPOINT = '5001/alloutlets';
export const ORDERS_ENDPOINT = '5001/createorder';
export const ORDERSSELLER_ENDPOINT = '5001/getorderseller';
export const ORDERSBUYER_ENDPOINT = '5001/getorderbuyer';
export const ACCEPTORDER_ENDPOINT = '5001/acceptOrder';
export const DECLINEORDER_ENDPOINT = '5001/declineOrder';
export const CHANGEORDERSTATUS_ENDPOINT = '5001/changeOrderStatus';
export const STORETOKENFCM_ENDPOINT = '5001/storetoken';
export const ORDERHISTORYDATA_ENDPOINT = '5001/orderhistorydata';
